[project]
name = "scipp-dev"
version = "0.1.0"
description = "Scipp development environment"
channels = ["conda-forge", "scipp"]
platforms = ["osx-arm64"]

[dependencies]
python = "3.10.*"
numpy = ">=1.21"
scipy = ">=1.7.0"
dask = ">=2024.11.2,<2025"
distributed = "*"
cmake = "3.30.3.*"
conan = "1.64.1.*"
ninja = "*"
pytest = "*"
hypothesis = "*"
matplotlib-base = "*"
h5py = "*"
pip = "*"

[tasks]
install-dev = "pip install -e ."
